// layout.tsx
import type { Metadata } from "next";
import { Rubik, Questrial } from "next/font/google";
import "./globals.css";
import Header from "../components/ui/Header";
import Footer from "../components/ui/Footer";

// import provider and store
import ReduxProvider from "@/components/partials/ReduxProvider";
import SProvider from "@/components/partials/SeasonProvider";

const rubik = Rubik({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  style: "normal",
  variable: "--font-rubik",
});

const questrial = Questrial({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Fresh Harvest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        lang="en"
        className={`${rubik.variable} ${questrial.variable} antialiased`}
      >
        {/* wrap everything */}
        <ReduxProvider>
          <SProvider>
            <Header />
          </SProvider>
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
